[tool.poetry]
name = "contract-master"
version = "0.1.0"
description = ""
authors = ["settler.cc"]
readme = "README.md"
packages = [{include = "contract_master"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
